Support clearing sessions of exported TTNv2 devices
TheThingsNetwork/lorawan-stack-migrate pull request #13
Opened 2020-12-22 23:15 UTC by neoaggelos

#### Summary

References https://github.com/TheThingsIndustries/lorawan-stack/issues/2417

#### Changes

- Add `--ttnv2.clear-session` flag.
- Update README with a notice to the users.

#### Testing

Test with `--ttnv2.clear-session` flag: Device session is deleted from TTN V2 after exporting.

#### Notes for Reviewers

Flag is disabled by default. Users must pass the flag explicitly, in order to avoid clearing the session keys by mistake.

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [X] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.

2020-12-23 11:10 UTC, johanstokking reviewed
I would clear the session by default, to be honest. It is really problematic if the session keys are in both servers.

I would have a flag `--dry-run` to indicate that it shouldn't clear, so people can see what's going on exactly.

---

Also, what happens on join?

2020-12-23 22:04 UTC, neoaggelos commented
Added a `--dry-run` flag, renamed `--ttnv2.clear-session` to `--ttnv2.clear-device-keys` and changed to clear the AppKey as well. This flag is also enabled by default, and the docs explicitly mention to verify any operations with `--dry-run` before actually running them.

2020-12-28 08:34 UTC, johanstokking requested changes

2020-12-28 08:34 UTC, johanstokking commented on README.md
> +- **IMPORTANT**: The migration from The Things Network Stack V2 to The Things Stack is one-way. Note that it is crucial that devices are handled by one Network Server at a time. In the commands below
Okay so `clear-device-keys` is by default `false`, but `dry-run` is by default also `false`?

Why don't we have one flag, `dry-run`, and if it's set, don't clear anything? And let `with-session` indicate what to clear and export.

So basically

`--dry-run` | `--with-session` | What happens
--- | --- | ---
`false` | `false` | reset root key, export root key but not session
`false` | `true` | reset session keys and root key, export all
`true` | `false` | no reset, export root key but not session
`true` | `true` | no reset, export all

2020-12-28 08:34 UTC, johanstokking commented on README.md
> +$ ttn-lw-migrate devices --source ttnv2 --ttnv2.clear-device-keys=true "mydevice" --dry-run --verbose < device_ids.txt > devices.json
This is where I find `clear-device-keys` confusing with `dry-run`.

2020-12-28 08:34 UTC, johanstokking commented on cmd/root.go
> +	rootCmd.PersistentFlags().Bool("dry-run", false, "Dry run")
Indicate what this means

2020-12-28 09:59 UTC, htdvisser reviewed
What exactly is the use case for clearing all device fields instead of just deleting the device from v2?

As far as I can think of, there are 3 scenarios:

- I want a dry run, where the CLI tells me what it will do.
- I want to migrate a device, but keep the session on v2 until my device does a new join on v3. In this case we should delete the root keys, but keep the session after migration.
- I want to migrate a device with its session. In this case we can delete the entire device registration from v2 after migration.

2021-01-04 16:50 UTC, rvolosatovs commented on cmd/root.go
> +	rootCmd.PersistentFlags().Bool("dry-run", false, "Dry run")
For reference, from `man 1 git push`:
```
       -n, --dry-run
           Do everything except actually send the updates.

```

2021-01-11 08:58 UTC, johanstokking commented on README.md
> +- The export process will halt if any errors occur. Execute any commands with the `--dry-run` flag first, to verify their result.
```suggestion
- The export process will halt if any error occurs.
- Execute commands with the `--dry-run` flag to verify if the outcome will be as expected.
```

2021-01-13 09:58 UTC, johanstokking approved these changes

2021-01-20 14:21 UTC, merged