Fail if exported devices contain invalid fields
TheThingsNetwork/lorawan-stack-migrate pull request #15
Opened 2020-12-24 00:24 UTC by neoaggelos

#### Summary

Validate exported devices exported, and fail if any fields are invalid.

#### Changes

- Use `ttnpb.EndDevice.ValidateFields` to validate that the exported device does not contain any errors
- Fail if validation fails
- Take this chance to replace `_` occurences with `-`, since `_` was an allowed character in TTN V2.

#### Testing

Export a device with name `some_device`.

- Without this change: No errors, device exported with invalid id, importing to TTS fails.
- With this change: Device exported as `some-device` instead, and all fields validated.

#### Checklist

- [X] Scope: The referenced issue is addressed, there are no unrelated changes.
- [ ] Documentation: Relevant documentation is added or updated.
- [ ] Changelog: Significant features, behavior changes, deprecations and fixes are added to `CHANGELOG.md`.

2020-12-28 09:30 UTC, johanstokking requested changes
Please be a bit less sloppy and look at the diff next time when requesting review

2020-12-28 09:30 UTC, johanstokking commented on cmd/util.go
> +	errFailedValidation = errors.DefineInvalidArgument("failed_validation", "failed to validate device")
Do not use "fail" or "failed" in errors. Errors indicate failure.

2020-12-28 09:30 UTC, johanstokking commented on cmd/util.go
> +func replaceUnderscores(s string) string {
Replace with what?

Please be clear and not require people to look at the implementation, even if it's a one liner, to see what's happening.

You can also do a package-global var like:

```go
var sanitizeID = strings.NewReplacer("-", "_")
```

This allows more advanced implementations without touching callers, when we implement some custom `Replace()` method

2020-12-28 09:30 UTC, johanstokking commented on cmd/util.go
> +		return errFormat.WithAttributes(
Attributes don't match with error description

2020-12-28 10:25 UTC, htdvisser reviewed
Nothing to add

2020-12-30 11:52 UTC, johanstokking approved these changes

2020-12-30 23:22 UTC, rvolosatovs commented on cmd/util.go
> +	if err := dev.ValidateFields(ttnpb.EndDeviceFieldPathsNested...); err != nil {
```suggestion
	if err := dev.ValidateFields(); err != nil {
```

2021-01-03 22:07 UTC, merged